[project]
name = "mcp_sqlite_server_nsdg"
version = "0.1.0"
description = "A Python MCP server."
readme = "README.md"
requires-python = ">=3.9"

[tool.mcp]
name = "io.github.thatikondanikhil/my-mcp-server"
